import { type Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import Header from "./component/Header";
import { jaJP } from "@clerk/localizations";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider localization={jaJP}>
      <html lang="ja">
        <body style={{ margin: 0 }}>
          <Header />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
